@extends('layouts.public')
@section('title', ($settings['school_name'] ?? 'School Manager').' | Home')
@section('content')
<section class="hero"><div class="container">
    <p class="eyebrow">Welcome to {{ strtoupper($settings['school_name'] ?? 'our school') }}</p>
    <h1>Where learning builds character, confidence and opportunity.</h1>
    <p>{{ $settings['mission'] ?? 'We provide a safe, inclusive and inspiring learning environment where every learner can thrive.' }}</p>
    <div class="hero-actions"><a class="btn" href="{{ route('admissions') }}">Apply for admission →</a><a class="btn secondary" href="{{ route('about') }}">Discover our school</a></div>
</div></section>
<section class="section"><div class="container">
    <div class="stat-strip"><div><span class="eyebrow">Academic year</span><strong>{{ $settings['academic_year'] ?: date('Y') }}</strong><span class="muted">{{ $settings['academic_term'] ?: 'Current term' }}</span></div><div><span class="eyebrow">Learning</span><strong>{{ $classes->count() }}</strong><span class="muted">Classes currently listed</span></div><div><span class="eyebrow">Community</span><strong>✓</strong><span class="muted">Learner-focused environment</span></div><div><span class="eyebrow">Admissions</span><strong>Open</strong><span class="muted">Online applications available</span></div></div>
</div></section>
@if($announcements->count())<section class="section alt"><div class="container"><div class="section-head"><div><p class="eyebrow">School updates</p><h2>Latest from {{ $settings['school_name'] }}</h2><p>Important announcements and information for our school community.</p></div></div><div class="grid">@foreach($announcements as $announcement)<article class="card"><span class="badge">Announcement</span><h3>{{ $announcement->title }}</h3><p>{{ $announcement->body }}</p>@if($announcement->published_at)<small class="muted">{{ \Carbon\Carbon::parse($announcement->published_at)->format('d M Y') }}</small>@endif</article>@endforeach</div></div></section>@endif
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Learning community</p><h2>Our classes</h2><p>Explore the classes currently configured by the school administration.</p></div><a class="btn secondary" href="{{ route('academics') }}">View academics</a></div><div class="grid">@forelse($classes as $class)<article class="card card-link"><div class="icon">{{ strtoupper(substr($class->name,0,1)) }}</div><h3>{{ $class->name }}</h3><p class="muted">{{ $class->stream ?: 'General stream' }}@if($class->academic_year) · {{ $class->academic_year }}@endif</p></article>@empty<div class="empty"><h3>Classes are being prepared</h3><p>The school administration will publish class information here as it is configured.</p><a class="btn secondary" href="{{ route('contact') }}">Contact the school</a></div>@endforelse</div></div></section>
@if($events->count())<section class="section alt"><div class="container"><div class="section-head"><div><p class="eyebrow">School calendar</p><h2>Upcoming events</h2><p>Keep up with important dates and activities.</p></div></div><div class="grid">@foreach($events as $event)<article class="card"><span class="badge">{{ \Carbon\Carbon::parse($event->event_date)->format('d M') }}</span><h3>{{ $event->title }}</h3><p><strong>{{ \Carbon\Carbon::parse($event->event_date)->format('l, d F Y') }}</strong>@if($event->location)<br>{{ $event->location }}@endif</p><p class="muted">{{ $event->description }}</p></article>@endforeach</div></div></section>@endif
<section class="section"><div class="container"><div class="card" style="background:linear-gradient(135deg,#0b3d7a,#1268d4);color:#fff;border:0"><div class="split"><div><p class="eyebrow" style="color:#bcd7ff">Join our community</p><h2 style="font-size:34px;margin:6px 0 10px">Give your child a strong foundation for the future.</h2><p style="color:#dce9fb">Learn more about our programmes or begin an admission application online.</p></div><div style="display:flex;align-items:center;justify-content:flex-end"><a class="btn" href="{{ route('admissions') }}">Begin admission</a></div></div></div></div></section>
@endsection