@extends('layouts.app')
@section('title', ($settings['school_name'] ?? 'School Manager').' | Home')
@section('body')
<nav class="nav"><a class="brand" href="{{ route('home') }}">{{ $settings['school_name'] ?? 'School Manager' }}</a><div class="navlinks"><a href="{{ route('about') }}">About</a><a href="{{ route('academics') }}">Academics</a><a href="{{ route('admissions') }}">Admissions</a><a href="{{ route('contact') }}">Contact</a><a class="btn" href="{{ route('login') }}">Admin Login</a></div></nav>
<section class="hero"><div class="container"><p><strong>WELCOME TO {{ strtoupper($settings['school_name'] ?? 'OUR SCHOOL') }}</strong></p><h1>Education built around character, knowledge and opportunity.</h1><p>{{ $settings['mission'] ?? '' }}</p><a class="btn" href="{{ route('admissions') }}">Apply for Admission</a> <a class="btn secondary" href="{{ route('about') }}">Discover Our School</a></div></section>
@if($announcements->count())<section class="section"><div class="container"><h2>Latest school updates</h2><div class="grid">@foreach($announcements as $announcement)<div class="card"><h3>{{ $announcement->title }}</h3><p>{{ $announcement->body }}</p>@if($announcement->published_at)<small>{{ \Carbon\Carbon::parse($announcement->published_at)->format('d M Y') }}</small>@endif</div>@endforeach</div></div></section>@endif
<section class="section"><div class="container"><h2>Our learning community</h2><p class="muted">{{ $settings['academic_year'] ? 'Academic year '.$settings['academic_year'].' · '.$settings['academic_term'] : 'Current academic programme' }}</p><div class="grid">@forelse($classes as $class)<div class="card"><h3>{{ $class->name }}{{ $class->stream ? ' — '.$class->stream : '' }}</h3><p>{{ $class->academic_year ? 'Academic year '.$class->academic_year : 'Current class' }}</p></div>@empty<div class="card"><h3>Classes</h3><p>Class information will appear here once entered by the school administrator.</p></div>@endforelse</div></div></section>
@if($events->count())<section class="section"><div class="container"><h2>Upcoming events</h2><div class="grid">@foreach($events as $event)<div class="card"><h3>{{ $event->title }}</h3><p><strong>{{ \Carbon\Carbon::parse($event->event_date)->format('D, d M Y') }}</strong>@if($event->location) · {{ $event->location }}@endif</p><p>{{ $event->description }}</p></div>@endforeach</div></div></section>@endif
<footer class="footer"><div class="container footer-grid"><div><h3>{{ $settings['school_name'] ?? 'School Manager' }}</h3><p>{{ $settings['vision'] ?? '' }}</p></div><div><h4>Explore</h4><p><a href="{{ route('about') }}">About</a><br><a href="{{ route('academics') }}">Academics</a><br><a href="{{ route('admissions') }}">Admissions</a></p></div><div><h4>Contact</h4><p>{{ $settings['school_phone'] ?: 'School office' }}<br>{{ $settings['school_email'] }}</p></div></div></footer>
@endsection
