@extends('layouts.app')
@section('title', 'Home | School Manager')
@section('body')
<nav class="nav"><a class="brand" href="{{ route('home') }}">School Manager</a><div class="navlinks"><a href="{{ route('about') }}">About</a><a href="{{ route('academics') }}">Academics</a><a href="{{ route('admissions') }}">Admissions</a><a href="{{ route('contact') }}">Contact</a><a class="btn" href="{{ route('login') }}">Admin Login</a></div></nav>
<section class="hero"><div class="container"><p><strong>WELCOME TO OUR SCHOOL</strong></p><h1>Growing confident learners for tomorrow.</h1><p>A modern digital school platform giving families easy access to admissions, academic information, school updates and secure payment services.</p><a class="btn" href="{{ route('admissions') }}">Apply for Admission</a> <a class="btn secondary" href="{{ route('about') }}">Discover Our School</a></div></section>
<section class="section"><div class="container"><h2>Everything families need</h2><p class="muted">A professional online presence connected to practical school management tools.</p><div class="grid"><div class="card"><h3>Online Admissions</h3><p>Submit an admission application from your phone or computer and receive confirmation.</p></div><div class="card"><h3>Academics</h3><p>Explore programmes, learning areas, facilities and the school's approach to education.</p></div><div class="card"><h3>M-Pesa Ready</h3><p>Designed for secure school fee and other school-charge payments through M-Pesa.</p></div><div class="card"><h3>School Updates</h3><p>Keep parents informed with announcements, events, news and important notices.</p></div></div></div></section>
<section class="section"><div class="container"><div class="card"><h2>Ready to join our school?</h2><p class="muted">Start the admission process online. The school administration will review your application and contact you.</p><a class="btn" href="{{ route('admissions') }}">Start Application</a></div></div></section>
<footer class="footer"><div class="container footer-grid"><div><h3>School Manager</h3><p>A complete school website and management foundation.</p></div><div><h4>Explore</h4><p><a href="{{ route('about') }}">About</a><br><a href="{{ route('academics') }}">Academics</a><br><a href="{{ route('admissions') }}">Admissions</a></p></div><div><h4>Contact</h4><p>Call the school office for assistance.</p></div></div></footer>
@endsection
