@extends('layouts.admin')
@section('title','Reports | School Manager')
@section('page_title','Reports')
@section('admin_content')
<div class="admin-page-head"><div><h1>School Reports</h1><p>Production-ready CBC academic, attendance, fees and admissions reporting generated {{ $generatedAt->format('d M Y H:i') }}.</p></div><div class="admin-actions"><a class="btn secondary" href="{{ route('admin.dashboard') }}">← Dashboard</a><button class="btn" onclick="window.print()">Print report</button></div></div>
<nav class="ops-nav">@foreach(['overview'=>'Overview','students'=>'Students','fees'=>'Fees','attendance'=>'Attendance','results'=>'CBC Results','admissions'=>'Admissions'] as $key=>$label)<a class="{{ $report === $key ? 'active' : '' }}" href="{{ route('admin.reports',['report'=>$key]) }}">{{ $label }}</a>@endforeach</nav>
<div class="stat-grid">@foreach([['Students',$studentCount],['Parents',$parentCount],['Teachers',$teacherCount],['Classes',$classCount]] as $card)<div class="stat"><span class="muted">{{ $card[0] }}</span><strong>{{ $card[1] }}</strong></div>@endforeach @if(isset($paymentTotal))<div class="stat"><span class="muted">Payments received</span><strong>KES {{ number_format($paymentTotal,2) }}</strong></div><div class="stat"><span class="muted">Outstanding fees</span><strong>KES {{ number_format($outstanding,2) }}</strong></div>@endif @if(isset($averageMarks))<div class="stat"><span class="muted">Average score</span><strong>{{ number_format($averageMarks,1) }}%</strong></div><div class="stat"><span class="muted">Missed assessments</span><strong>{{ $missedAssessmentCount }}</strong></div>@endif</div>
@if(isset($students))<section class="card report-section"><div class="section-head"><div><h2>Students</h2><p>Current learner register and fee balances.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Admission</th><th>Name</th><th>Class</th><th>Parent</th><th>Balance</th></tr></thead><tbody>@forelse($students as $student)<tr><td>{{ $student->admission_number }}</td><td><strong>{{ $student->name }}</strong></td><td>{{ $student->class_label ? $student->class_label . ($student->stream ? ' - '.$student->stream : '') : ($student->class_name ?: '—') }}</td><td>{{ $student->parent_label ?: '—' }}</td><td>KES {{ number_format((float)($student->fee_balance ?? 0),2) }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state">No students found.</div></td></tr>@endforelse</tbody></table></div></section>@endif
@if(isset($payments))<section class="card report-section"><h2>Fees & Payments</h2><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Student</th><th>Amount</th><th>Status</th><th>M-Pesa receipt</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->created_at }}</td><td>{{ $payment->student_name ?: $payment->student_id }}</td><td><strong>KES {{ number_format((float)($payment->{$paymentAmountColumn} ?? 0),2) }}</strong></td><td>{{ ucfirst($payment->status ?? '—') }}</td><td>{{ $payment->mpesa_receipt ?? '—' }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state">No payments found.</div></td></tr>@endforelse</tbody></table></div></section>@endif
@if(isset($attendance))<section class="card report-section"><h2>Attendance</h2><p class="muted">Present: {{ $attendanceSummary['present'] ?? 0 }} · Absent: {{ $attendanceSummary['absent'] ?? 0 }} · Late: {{ $attendanceSummary['late'] ?? 0 }} · Excused: {{ $attendanceSummary['excused'] ?? 0 }}</p><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Student</th><th>Status</th></tr></thead><tbody>@forelse($attendance as $row)<tr><td>{{ $row->attendance_date }}</td><td>{{ $row->student_name }}</td><td>{{ ucfirst($row->status) }}</td></tr>@empty<tr><td colspan="3"><div class="empty-state">No attendance records found.</div></td></tr>@endforelse</tbody></table></div></section>@endif
@if(isset($results))<section class="card report-section cbc-report"><div class="section-head"><div><span class="page-kicker">Competency-Based Assessment</span><h2>CBC Academic Achievement Report</h2><p>Learning areas are reported using achievement levels, points and teacher/assessor evidence. A missed assessment is not converted into zero marks.</p></div></div><div class="cbc-summary">@foreach(['EE1'=>'Exceeding 1','EE2'=>'Exceeding 2','ME1'=>'Meeting 1','ME2'=>'Meeting 2','AE1'=>'Approaching 1','AE2'=>'Approaching 2','BE1'=>'Below 1','BE2'=>'Below 2'] as $code=>$label)<span><b>{{ $code }}</b>{{ $cbcLevelSummary[$code]??0 }} records</span>@endforeach</div><div class="table-wrap"><table class="table"><thead><tr><th>Assessment</th><th>Learner</th><th>Learning area</th><th>Score</th><th>Achievement level</th><th>Points</th><th>Evidence / status</th></tr></thead><tbody>@forelse($results as $row)@php $missed=$row->assessment_status==='missed'; $code=$missed?'MISSED':($row->achievement_level?:'—'); $label=$missed?'Missed Assessment':$code; @endphp<tr><td>{{ $row->exam_name }}</td><td><strong>{{ $row->student_name }}</strong><small>{{ $row->admission_number }}</small></td><td>{{ $row->subject_name }}</td><td>{{ $row->marks===null?'—':number_format((float)$row->marks,1).'/100' }}</td><td><span class="achievement">{{ $code }}</span><small>{{ $label }}</small></td><td>{{ $row->achievement_points===null?'—':$row->achievement_points }}</td><td>{{ $missed?'Missed assessment — follow-up required.':'Achievement level recorded.' }}</td></tr>@empty<tr><td colspan="7"><div class="empty-state">No CBC results found.</div></td></tr>@endforelse</tbody></table></div></section>@endif
@if(isset($applications))<section class="card report-section"><h2>Admissions</h2><p class="muted">@foreach($applicationSummary as $status=>$total)<strong>{{ ucfirst($status) }}:</strong> {{ $total }} &nbsp; @endforeach</p><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Student</th><th>Requested class</th><th>Status</th></tr></thead><tbody>@forelse($applications as $application)<tr><td>{{ $application->created_at }}</td><td>{{ $application->student_name }}</td><td>{{ $application->requested_class }}</td><td>{{ ucfirst($application->status) }}</td></tr>@empty<tr><td colspan="4"><div class="empty-state">No applications found.</div></td></tr>@endforelse</tbody></table></div></section>@endif
<style>.report-section{margin-bottom:16px}.report-section h2{margin-top:0}.cbc-summary{display:grid;grid-template-columns:repeat(8,1fr);gap:7px;margin:14px 0}.cbc-summary span{padding:9px;background:#f7faff;border:1px solid #e1e9f3;border-radius:8px;text-align:center;font-size:9px;color:#718096}.cbc-summary b{display:block;color:#1769df;font-size:11px}.cbc-report .table td small{display:block;color:#8995a7;font-size:9px;margin-top:3px}.achievement{display:inline-block;padding:5px 7px;border-radius:7px;background:#edf4ff;color:#1769df;font-weight:900;font-size:10px}.admin-main .stat strong{font-size:24px}@media(max-width:1000px){.cbc-summary{grid-template-columns:repeat(4,1fr)}}@media(max-width:600px){.cbc-summary{grid-template-columns:repeat(2,1fr)}}@media print{.sidebar,.admin-top,.admin-breadcrumb,.admin-actions,.ops-nav{display:none!important}.admin-main{padding:0}.report-section{box-shadow:none!important;break-inside:avoid}}</style>
@endsection
