<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CBC Report Card — {{ $student->name }}</title>
<style>
*{box-sizing:border-box}
html,body{margin:0;padding:0}
body{background:#eef2f6;color:#172437;font-family:Arial,Helvetica,sans-serif;font-size:8px;line-height:1.18}
.sheet{width:100%;max-width:900px;margin:12px auto;background:#fff;border:1px solid #d6dee8;box-shadow:0 7px 22px rgba(27,46,72,.10);padding:12px}
.actions{margin:0 auto 9px;display:flex;justify-content:center;gap:7px;flex-wrap:wrap}
.actions a,.actions button{padding:7px 12px;border:0;background:#173f6d;color:#fff;border-radius:5px;cursor:pointer;text-decoration:none;font-size:9px;font-weight:700}
.actions a{background:#247653}
.success,.errors{padding:7px 9px;margin:0 auto 7px;max-width:900px;border-radius:5px;font-size:8px}
.success{background:#eaf7ef;border:1px solid #c9e6d3;color:#216d45}.errors{background:#fff1f0;border:1px solid #efc9c5;color:#9a3027}.errors ul{margin:0;padding-left:16px}
.header{border:1px solid #ccd7e3;background:#fff}
.header-top{position:relative;min-height:67px;padding:9px 12px 8px;text-align:center;border-bottom:3px solid #173f6d;background:#f7f9fc}
.school-badge{display:block;width:38px;height:38px;margin:0 auto 3px;object-fit:contain}
.school-name{margin:0;color:#12355d;font-size:16px;line-height:1.04;text-transform:uppercase;letter-spacing:.45px}
.school-subtitle{margin:2px 0 0;color:#68788d;font-size:6.6px;text-transform:uppercase;letter-spacing:.65px}
.document-label{display:inline-block;margin-top:4px;padding:2px 7px;border:1px solid #cbdbea;border-radius:10px;background:#eaf1f8;color:#173f6d;font-size:6px;font-weight:700;text-transform:uppercase;letter-spacing:.45px}
.header-meta{width:100%;border-collapse:collapse;background:#fff}.header-meta td{width:25%;padding:4px 6px;border-right:1px solid #dce3eb;text-align:center}.header-meta td:last-child{border-right:0}.header-meta small{display:block;color:#7a8798;text-transform:uppercase;font-size:5.5px;font-weight:700;letter-spacing:.25px}.header-meta strong{display:block;margin-top:1px;color:#20344d;font-size:7.3px;line-height:1.1}.status-complete{color:#18704c!important}.status-incomplete{color:#a55c16!important}
.title{text-align:center;padding:6px 0 5px}.title h1{margin:0;color:#173f6d;font-size:11.5px;letter-spacing:.35px}.title p{margin:2px 0 0;color:#6a788a;font-size:6.6px}
.identity{width:100%;border-collapse:separate;border-spacing:3px;margin:0 -3px 5px;width:calc(100% + 6px)}.identity td{width:25%;padding:5px 6px;border:1px solid #d4dde7;background:#f8fafc;vertical-align:top}.identity small{display:block;color:#718095;text-transform:uppercase;font-size:5.5px;font-weight:700;letter-spacing:.3px}.identity strong{display:block;margin-top:2px;color:#172c47;font-size:7.4px}
.section-title{margin:5px 0 3px;color:#173f6d;font-size:7px;font-weight:700;text-transform:uppercase;letter-spacing:.55px;border-left:3px solid #173f6d;padding-left:5px}
.table{width:100%;border-collapse:collapse;table-layout:fixed}.table th{padding:4px 4px;background:#173f6d;color:#fff;border:1px solid #173f6d;text-align:left;font-size:6.2px;text-transform:uppercase;letter-spacing:.15px}.table td{padding:3.5px 4px;border:1px solid #d5dee8;font-size:6.9px;vertical-align:middle}.table tbody tr:nth-child(even) td{background:#f8fafc}.table th:nth-child(1){width:24%}.table th:nth-child(2){width:10%;text-align:center}.table th:nth-child(3){width:19%;text-align:center}.table th:nth-child(4){width:9%;text-align:center}.table th:nth-child(5){width:38%}.table td:nth-child(2),.table td:nth-child(3),.table td:nth-child(4){text-align:center}.table td strong{font-size:7px;color:#1e3048}.subject-code{color:#7d8999;font-size:5.5px;letter-spacing:.2px}.level{font-weight:700;text-align:center;background:#e9f2fc!important;color:#145b9f}.missed{background:#fff0f0!important;color:#a3212c;font-weight:700;text-align:center}
.summary{width:100%;border-collapse:separate;border-spacing:3px;margin:5px -3px 0;width:calc(100% + 6px)}.summary td{width:25%;border:1px solid #d2dce6;padding:4px;text-align:center;background:#fff}.summary b{display:block;color:#173f6d;font-size:10.5px;line-height:1}.summary span{display:block;margin-top:2px;color:#718095;font-size:5.4px;text-transform:uppercase;letter-spacing:.2px}
.two-col{width:100%;border-collapse:separate;border-spacing:3px;margin:4px -3px 0;width:calc(100% + 6px)}.two-col>tbody>tr>td{width:50%;vertical-align:top}.panel{border:1px solid #d3dde7;background:#f8fafc;padding:4px 5px}.panel h3{margin:0 0 3px;color:#173f6d;font-size:6.5px;text-transform:uppercase;letter-spacing:.4px}.panel p{margin:2px 0;color:#536276;font-size:5.9px}.scale{width:100%;border-collapse:collapse}.scale td{border:1px solid #d9e1e9;padding:2px 4px;font-size:5.9px;background:#fff}.scale td:first-child{width:16%;font-weight:700;color:#173f6d;text-align:center}.attendance{width:100%;border-collapse:collapse}.attendance td{padding:1.8px 3px;font-size:6px;color:#536276;border-bottom:1px solid #e0e6ec}.attendance td:last-child{text-align:right;font-weight:700;color:#20344d}.parent-inline{margin-top:3px!important}
.note{margin-top:3px;padding:4px 6px;border-left:3px solid #173f6d;background:#f3f6f9;color:#56657a;font-size:5.8px}.note strong{color:#243852}
.signatures{width:100%;border-collapse:separate;border-spacing:6px;margin:6px -6px 0;width:calc(100% + 12px)}.signatures td{width:33.333%;height:58px;padding:2px 4px 0;border-top:1px solid #687789;text-align:center;color:#34445a;font-size:6.6px;font-weight:700;vertical-align:top}.signature-image{display:block;height:29px;max-width:110px;margin:0 auto 1px;object-fit:contain}.stamp-image{display:block;height:29px;max-width:62px;margin:0 auto 1px;object-fit:contain}.signature-placeholder{height:29px;margin-bottom:1px}.signatures small{display:block;margin-top:1px;color:#7d8998;font-weight:400;font-size:5.4px}.parent-signed{display:inline-block;margin-top:1px;padding:1.5px 4px;border-radius:7px;background:#eaf7ef;color:#247443;font-size:5.2px}
.parent-sign-box{margin:6px 0 0;padding:6px;border:1px solid #d5e0eb;background:#f8fafc;border-radius:5px}.parent-sign-box h3{margin:0 0 3px;color:#173f6d;font-size:7px}.parent-sign-box p{margin:2px 0;color:#66758a;font-size:6.4px}.parent-sign-box input{max-width:100%;font-size:7px}.parent-sign-box button{margin-top:3px;padding:5px 8px;border:0;border-radius:4px;background:#173f6d;color:#fff;font-weight:700;font-size:7px;cursor:pointer}
.footer{margin-top:3px;padding-top:3px;border-top:1px solid #dbe2e9;text-align:center;color:#8793a2;font-size:5.3px}
@page{size:A4 portrait;margin:5mm}
@media print{html,body{background:#fff}.sheet{max-width:none;width:100%;margin:0;border:0;box-shadow:none;padding:0}.actions,.parent-sign-box,.success,.errors{display:none}.header,.identity,.summary,.two-col,.signatures,.table,.note{break-inside:avoid;page-break-inside:avoid}.table tr{break-inside:avoid;page-break-inside:avoid}.footer{margin-top:2px}}
@media(max-width:650px){.sheet{padding:8px}.school-name{font-size:14px}.identity,.summary,.two-col,.signatures{display:block;width:100%;margin:0}.identity td,.summary td,.two-col>tbody>tr>td,.signatures td{display:block;width:100%;margin:3px 0}.table th,.table td{padding:3px 2px}}
</style>
</head>
<body>
@if(empty($downloadMode))
<div class="actions"><button onclick="window.print()">Print / Save as PDF</button>@if(auth()->user() && in_array(auth()->user()->role,['admin','manager'],true))<a href="{{ route('admin.report-cards.download',[$student->id,$exam->id]) }}">Download report card</a>@else<a href="{{ route('portal.report-cards.download',[$student->id,$exam->id]) }}">Download report card</a>@endif</div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@endif
<main class="sheet">
<header class="header"><div class="header-top">@if(!empty($schoolBadgeData))<img class="school-badge" src="{{ $schoolBadgeData }}" alt="School badge">@endif<h1 class="school-name">{{ $schoolName }}</h1><p class="school-subtitle">Competency Based Assessment • Learner Progress Report</p><span class="document-label">Official Academic Record</span></div><table class="header-meta"><tr><td><small>Assessment</small><strong>{{ $exam->name }}</strong></td><td><small>Term</small><strong>{{ $exam->term }}</strong></td><td><small>Academic Year</small><strong>{{ $exam->academic_year }}</strong></td><td><small>Status</small><strong class="{{ $complete ? 'status-complete' : 'status-incomplete' }}">{{ $complete ? 'Complete' : 'Incomplete' }}</strong></td></tr></table></header>
<section class="title"><h1>COMPETENCY BASED CURRICULUM REPORT CARD</h1><p>{{ $exam->term }} • {{ $exam->name }} • {{ $exam->academic_year }}</p></section>
<table class="identity"><tr><td><small>Learner Name</small><strong>{{ $student->name }}</strong></td><td><small>Admission Number</small><strong>{{ $student->admission_number }}</strong></td><td><small>Grade / Class</small><strong>{{ $student->class_label ?: $student->class_name ?: '—' }}{{ $student->class_stream ? ' - '.$student->class_stream : '' }}</strong></td><td><small>Report Status</small><strong class="{{ $complete ? 'status-complete' : 'status-incomplete' }}">{{ $complete ? 'Complete' : 'Incomplete' }}</strong></td></tr></table>
<div class="section-title">Learning Area Performance</div><table class="table"><thead><tr><th>Learning Area</th><th>Score</th><th>Achievement Level</th><th>Points</th><th>Teacher / Assessor Remark</th></tr></thead><tbody>@foreach($results as $result)<tr><td><strong>{{ $result->subject_name }}</strong>@if($result->subject_code)<br><span class="subject-code">{{ $result->subject_code }}</span>@endif</td><td>{{ $result->marks===null?'—':number_format((float)$result->marks,1) }}</td><td class="{{ $result->assessment_status==='missed'?'missed':'level' }}">{{ $result->assessment_status==='missed'?'MISSED':$result->achievement_level }}</td><td>{{ $result->achievement_points ?? '—' }}</td><td>{{ $result->remarks ?: $result->display_remark }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td><b>{{ $results->count() }}</b><span>Learning Areas</span></td><td><b>{{ $results->where('assessment_status','missed')->count() }}</b><span>Missed Assessments</span></td><td><b>{{ $points !== null ? $points : '—' }}</b><span>Total Achievement Points</span></td><td><b>{{ $average !== null ? number_format($average,1).'%' : '—' }}</b><span>Average Score</span></td></tr></table>
<table class="two-col"><tr><td><div class="panel"><h3>CBC Achievement Scale</h3><table class="scale"><tr><td>EE</td><td>Exceeding Expectation</td></tr><tr><td>ME</td><td>Meeting Expectation</td></tr><tr><td>AE</td><td>Approaching Expectation</td></tr><tr><td>BE</td><td>Below Expectation</td></tr></table><p>Performance levels: EE1, EE2, ME1, ME2, AE1, AE2, BE1 and BE2.</p></div></td><td><div class="panel"><h3>Attendance Record</h3><table class="attendance"><tr><td>Present</td><td>{{ $attendance['present'] ?? 0 }}</td></tr><tr><td>Absent</td><td>{{ $attendance['absent'] ?? 0 }}</td></tr><tr><td>Late</td><td>{{ $attendance['late'] ?? 0 }}</td></tr><tr><td>Excused</td><td>{{ $attendance['excused'] ?? 0 }}</td></tr></table>@if($parent)<p class="parent-inline"><strong>Parent / Guardian:</strong> {{ $parent->name }}</p>@endif</div></td></tr></table>
<div class="note"><strong>Important:</strong> Missed assessments are explicitly recorded as MISSED and are not treated as zero marks. Achievement points are awarded only where a valid performance level is recorded.</div>
@if(!empty($canParentSign) && !$parentSignedAt)<div class="parent-sign-box"><h3>Parent / Guardian acknowledgement</h3><p>Please review this report card carefully. You are the only person who signs this report after reviewing it. Upload an image of your handwritten signature to acknowledge the report.</p><form method="POST" action="{{ route('portal.report-cards.sign',[$student->id,$exam->id]) }}" enctype="multipart/form-data">@csrf<input type="file" name="parent_signature" accept="image/jpeg,image/png,image/webp" required><button type="submit">Sign report card</button></form></div>@endif
<table class="signatures"><tr><td>@if(!empty($classTeacherSignatureData))<img class="signature-image" src="{{ $classTeacherSignatureData }}" alt="Class teacher signature">@else<div class="signature-placeholder"></div>@endif{{ $classTeacher ? $classTeacher->name : 'Class Teacher' }}<small>Class Teacher / Assessor · System signature</small></td><td>@if(!empty($parentSignatureData))<img class="signature-image" src="{{ $parentSignatureData }}" alt="Parent signature">@else<div class="signature-placeholder"></div>@endif{{ $parent ? $parent->name : 'Parent / Guardian' }}<small>Parent / Guardian · Signature &amp; Date</small>@if($parentSignedAt)<span class="parent-signed">Signed {{ \Carbon\Carbon::parse($parentSignedAt)->format('d M Y H:i') }}</span>@endif</td><td>@if(!empty($headSignatureData))<img class="signature-image" src="{{ $headSignatureData }}" alt="Head of Institution signature">@else<div class="signature-placeholder"></div>@endif{{ $headOfInstitution ? $headOfInstitution->name : 'Head of Institution' }}<small>Head of Institution · System signature &amp; Official Stamp</small>@if(!empty($schoolStampData))<img class="stamp-image" src="{{ $schoolStampData }}" alt="Official school stamp">@endif</td></tr></table>
<footer class="footer">Generated by {{ $schoolName }} • Competency Based Assessment Report • This document is system generated.</footer>
</main>
</body>
</html>
