@extends('layouts.admin')
@section('title','Payments | School Manager')
@section('page_title','Payments & Fees')
@section('admin_content')
<div class="admin-page-head"><div><h1>Fees & Payments</h1><p>Monitor fee collections, M-Pesa STK activity, verification status and outstanding balances.</p></div><div class="admin-actions"><a class="btn secondary" href="{{ route('admin.dashboard') }}">← Dashboard</a><a class="btn" href="{{ route('admin.payments.create') }}">+ Record payment</a></div></div>
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<div class="card" style="margin-bottom:16px"><form method="get" class="search"><input name="search" value="{{ request('search') }}" placeholder="Search student, admission, phone or receipt"><select name="status"><option value="">All statuses</option>@foreach(['pending','completed','failed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button type="submit">Filter</button>@if(request('search')||request('status'))<a href="{{ route('admin.payments.index') }}">Clear</a>@endif</form></div>
<div class="card"><div class="section-head"><div><h2>Payment watch</h2><p>Use verification status and channel to distinguish pending STK prompts from confirmed receipts.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Student</th><th>Payer</th><th>Channel</th><th>Amount</th><th>Reference / Receipt</th><th>Status</th><th>Verification</th></tr></thead><tbody>@forelse($payments as $p)<tr><td>{{ $p->created_at }}</td><td><strong>{{ $p->student_name ?: '—' }}</strong><br><small>{{ $p->admission_number ?: '—' }}</small></td><td>{{ $p->payer_name ?: ($p->parent_phone ?: '—') }}</td><td>{{ $p->channel ?: 'Manual' }}</td><td><strong>KES {{ number_format((float)$p->amount,2) }}</strong></td><td>{{ $p->mpesa_receipt ?: ($p->account_reference ?: '—') }}</td><td><span class="status-badge {{ in_array($p->status,['completed','paid','success'])?'success':($p->status==='failed'?'danger':'warning') }}">{{ ucfirst($p->status) }}</span></td><td><span class="status-badge {{ ($p->verification_status ?? 'pending')==='verified'?'success':(($p->verification_status ?? 'pending')==='rejected'?'danger':'warning') }}">{{ ucfirst($p->verification_status ?? 'pending') }}</span></td></tr>@empty<tr><td colspan="8"><div class="empty-state"><strong>No payments found</strong><span>Record a payment or wait for M-Pesa transactions to arrive.</span></div></td></tr>@endforelse</tbody></table></div>{{ $payments->links() }}</div>
@endsection
