@extends('layouts.app')
@section('title', ucfirst($user->role).' Dashboard | School Manager')
@section('body')
<div class="admin-shell">
<header class="admin-top"><div><strong>School Manager</strong><div style="font-size:13px;opacity:.75">{{ ucfirst($user->role) }} Portal</div></div><form method="post" action="{{ route('portal.logout') }}"><input type="hidden" name="_token" value="{{ csrf_token() }}"><button class="btn secondary" type="submit">Sign out</button></form></header>
<main class="admin-main" style="max-width:1200px;margin:auto">
<p class="eyebrow">{{ ucfirst($user->role) }} dashboard</p><h1>Welcome, {{ $user->name }}</h1><p class="muted">Your personalised school portal.</p>
@if($profile && $profile->portal_type === 'teacher')
<div class="stat-grid" style="margin:25px 0"><div class="stat"><span class="muted">Account</span><strong>Teacher</strong></div><div class="stat"><span class="muted">Subjects</span><strong>{{ $subjects->count() }}</strong></div><div class="stat"><span class="muted">Learners</span><strong>{{ $teacherStudentCount }}</strong></div><div class="stat"><span class="muted">Employee No.</span><strong>{{ $teacher->employee_number ?? '—' }}</strong></div></div>
<section class="card"><h2>Teaching profile</h2><p><strong>Name:</strong> {{ $teacher->name ?? $user->name }}</p><p><strong>Email:</strong> {{ $teacher->email ?? $user->email }}</p><p><strong>Phone:</strong> {{ $teacher->phone ?? 'Not provided' }}</p></section>
<section class="card" style="margin-top:20px"><h2>My subjects</h2><div class="stat-grid">@forelse($subjects as $subject)<div class="card" style="background:#f8faff"><h3>{{ $subject->name }}</h3><p class="muted">Code: {{ $subject->code ?: 'N/A' }}</p></div>@empty<p class="muted">No subjects have been assigned yet.</p>@endforelse</div></section>
<section class="card" style="margin-top:20px"><h2>Classroom overview</h2><p class="muted">You currently have access to {{ $teacherStudentCount }} learners in the school system. Attendance, assessment and class-management tools can be connected here as the school workflow expands.</p></section>
@elseif($profile && $profile->portal_type === 'pupil')
<div class="stat-grid" style="margin:25px 0"><div class="stat"><span class="muted">Account</span><strong>Pupil</strong></div><div class="stat"><span class="muted">Linked pupils</span><strong>{{ $students->count() }}</strong></div><div class="stat"><span class="muted">Portal status</span><strong>Active</strong></div><div class="stat"><span class="muted">Email</span><strong style="font-size:18px">{{ $user->email }}</strong></div></div>
<section class="card"><h2>My academic profile</h2>@forelse($students as $student)<div class="card" style="margin-top:15px;background:#f8faff"><h3>{{ $student->name }}</h3><p><strong>Admission:</strong> {{ $student->admission_number }}</p><p><strong>Class:</strong> {{ $student->class_name ?: 'Not assigned' }}</p><p><strong>Fee balance:</strong> KES {{ number_format((float)$student->fee_balance, 2) }}</p></div>@empty<p class="muted">Your pupil record is not yet linked. Please contact the school office.</p>@endforelse</section>
@else
<div class="stat-grid" style="margin:25px 0"><div class="stat"><span class="muted">Account</span><strong>{{ ucfirst($user->role) }}</strong></div><div class="stat"><span class="muted">Linked pupils</span><strong>{{ $students->count() }}</strong></div><div class="stat"><span class="muted">Portal status</span><strong>Active</strong></div><div class="stat"><span class="muted">Email</span><strong style="font-size:18px">{{ $user->email }}</strong></div></div>
<section class="card"><h2>Linked pupils</h2><p class="muted">Monitor the learners connected to your portal account.</p>@forelse($students as $student)<div class="card" style="margin-top:15px;background:#f8faff"><h3>{{ $student->name }}</h3><p><strong>Admission:</strong> {{ $student->admission_number }} &nbsp; <strong>Class:</strong> {{ $student->class_name ?: 'Not assigned' }}</p><p><strong>Fee balance:</strong> KES {{ number_format((float)$student->fee_balance, 2) }}</p></div>@empty<div class="empty"><h3>No pupils linked yet</h3><p>Your account is active, but no pupil has been linked to it yet.</p></div>@endforelse</section>
@endif
</main></div>
@endsection
